spring.application.name=hexagonal

# ========================================
# CONFIGURACION H2 DATABASE
# ========================================

# URL de la base de datos H2 en memoria
spring.datasource.url=jdbc:h2:file:./data/bancodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Dialecto de H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Crear/actualizar tablas automaticamente
spring.jpa.hibernate.ddl-auto=update

# Mostrar SQL en consola (para debug)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ========================================
# H2 CONSOLE (Interfaz Web)
# ========================================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
